const statements = {
  login: "ورود و عضویت",
  pishgaman: "پیشگامان",
  damane: "دامنه فناوری",
  mobile: "گوشی موبایل",
  kapshan: "کاپشن مردانه",
  porbazdid: "محصولات پر بازدید اخیر",
  montakhab: "منتخب جدید ترین کالا ها",
  goTop: "برگشت به بالا",
  takhfif: "تخفیف های شگفت انگیز",
  findWhat: "دنبال چی هستی؟",
  webEmail: "Peymanhc@gmail.com",
  phone: "09165549757",
  showall: "مشاهده همه",
  sold: "فروش رفته",
  currency: "تومان",
  newprice: "قیمت جدید",
  lastprice: "قیمت قبل",
  basket:"سبد خرید",
  addtobasket: "افزودن به سبد خرید",
  propetydetail: "برخی از ویژگی های این محصول",
  max: "حداکثر تا",
  day: "روز",
  deliverd: "تحویل داده میشود",
  successSell:"فروش موفق برای این محصول",
  zemanat:"این کالا دارای ضمانت بازگشت وجه به مدت دو هفته است",
  category:"دسته",
  brand:"برند",
  description:"توضیحات",
  allDescriptions:"توضیحات تکمیلی",
  userComments:"نظرات کاربران",
  sellerInfo:"اطلاعات فروشنده",
  sellerQues:"پرسش از فروشنده",
  name:"نام شما",
  emailtest:"you@Example.com",
  quesInfo:"جزییات پرسش شما ...",
  quesSubmit:"ثبت پرسش",
  comment:"دیدگاه",
  fromRate:"امتیاز از",
  commentRole:"قوانین دیدگاه",
  commentRole_1:"از ارسال دیدگاه های توهین آمیز پرهیز کنید",
  commentRole_2:"لطفا نظر واقعی خود را بنویسید",
  commentRole_3:"دیدگاه شما میتواند به خرید دیگران کمک کند",
  comments:"لیست دیدگاه ها",
  yourComment:"دیدگاه شما",
  sendYourComment:"دیدگاه خود را بنویسید",
  sendCommentrole:"نشانی ایمیل شما منتشر نخواهد شد. بخش‌های موردنیاز علامت‌گذاری شده‌اند *",
  yourRate:"امتیاز شما",
  name:"نام",
  email:"ایمیل",
  savedataText:" ذخیره نام، ایمیل و وبسایت من در مرورگر برای زمانی که دوباره دیدگاهی می‌نویسم.",
  submitComment:"ثبت نظر",
  relatedProducts:"محصولات مرتبط",
  productName:"نام محصول",
  wishesTitle:"لیست علاقه مندی ها",
  emptyWishes:"سبد خرید شما خالی است",
  wishesTitle2:" لیست علاقه مندی های من در فروشگاه هادوی ",
  Account:"حساب کاربری",
  loginTitle:"ورود به حساب کاربری",
  nameOrEmail:"نام یا آدرس ایمیل *",
  password:"رمز عبور *",
  open:"ورود",
  forgotpass:"رمز عبور را فراموش کرده اید ؟",
  savePassword:"مرا به خاطر داشته باش",
  newUser:" کاربر جدید هستید؟ ",
  register:"ثبت نام",
  registeronWeb:"عضویت در سایت",
  ConfrimPassword:"تکرار رمز عبور",
  youHaveAnAccount:"قبلا ثبت نام کرده اید",
  resetPassword:"بازگردانی رمز عبور",
  blogTitle:"نوشته‌های بلاگ",
  importantList:"فهرست مهم",
  bestDiscount:"بهترین محصولات تخفیفی",
  more:"بیشتر",
  bestpersonal:"بهترین لوازم شخصی ",
  besteat:"بهترین  خوراکی ها ",
  totalPrice:"مجموع کل سبد خرید",
  totalpriceTxt:"قیمت کل",
  total:"مجموع",
  payTxt:"اقدام به پرداخت",
  updatecart:"به روز رسانی سبد ",
  submitdiscountCode:"اعمال کد تخفیف",
  discountCode:"کد تخفیف",
  order:"پیگیری سفارش",
  orderTitle:"برای رهگیری سفارشتان شماره سفارش و ایمیلی که درهنگام ثبت سفارش وارد کردید را در این قسمت وارد و کلید رهگیری را فشار دهید.",
  ordercode:"شماره سفارش",
  ordercodeInput:"شماره سفارش در ایمیل ارسال شده به شما موجود است.",
  emailorder:"ایمیل صورتحساب",
  emailorderInput:"ایمیلی که در هنگام ثبت سفارش وارد کردید.",
  tracking:"رهگیری",
  checkout:"تسویه حساب",
  price:"قیمت",
  categoryProducts:"دسته بندی محصولات",
  store:"فروشگاه",
  priceRange:"محدوده قیمت",
  filter_1:"مرتب سازی بر اساس محبوبیت",
  filter_2:"مرتب سازی بر اساس میانگین رتبه",
  filter_3:"مرتب سازی بر اساس جدیدترین",
  filter_4:"مرتب سازی بر اساس هزینه: کم به زیاد",
  filter_5:"مرتب سازی بر اساس هزینه: زیاد به کم",
  payDetail:"جزئیات پرداخت",
  yourOrder:"سفارش شما",
  family:"نام خانوادگی",
  company:"شرکت",
  ostan:"استان",
  shahr:"شهر",
  khiaban:"خیابان",
  address:"آدرس",
  postalcode:"کد پستی",
  pelak:"پلاک",
  telnum:"تلفن",
  emailaddress:"آدرس ایمیل",
  submitPay:"ثبت سفارش"
};
export default statements;
